### ISSUE TITLE
Email on failure

### ISSUE THREAD

**Issue by jonaskello** [aptible/supercronic#14]
Is there some way to configure supercronic to send an email if a job fails?

**Comment by krallin** [comment]
No. What we do for ourselves is use a cron job monitoring tool (we use [Dead Man's Snitch](https://deadmanssnitch.com) for it, but it's not the only game in town) to alert us when jobs don't run. Since Supercronic executes your commands using a shell, you can usually just do this in your crontab:

```
job: do-the-job && curl https://nosnch.in/$JOB_SNITCH_ID
```

Then, you just set the `JOB_SNITCH_ID` environment variable when running the container.
