### ISSUE TITLE
How to run this in Dockerfile?

### ISSUE THREAD

**Issue by fracz** [aptible/supercronic#15]
After I read the documentation and a few examples, it is still not clear to me how to start the supercronic during container startup.

When I want to start the supercronic in a container that already have a `CMD`, I can't add another `CMD supercronic /crontab` because it will overwrite the original.

I can't put `RUN supercronic /crontab` in `Dockerfile` because the container will never start.

Finally, when I `RUN` the supercronic in backgroudn, I can neither access the supercronic logs with `docker logs` nor they are stored in any file.

What is the best practice to run supercronic in an existing container?

My case: I have an application container based on [`php7.1-apache container`](https://hub.docker.com/_/php/) and I want to run a command periodically inside this container. I want the crontab to be activated automatically when the container starts. I want to be able to access logs of both apache and supercronic.

**Comment by krallin** [comment]
Running Supercronic and Apache together isn't any different from running any other combination of multiple processes in the same container. Here are a few relevant links:

- https://docs.docker.com/engine/admin/multi-service_container/
- https://stackoverflow.com/questions/19948149/can-i-run-multiple-programs-in-a-docker-container

That said, in general, I would personally recommend running separate processes in separate containers.

**Comment by 5zymon** [comment]
This is little bit old topic, but I think we had similar issues with @fracz 

What I did in the end, I've created separate container only for cronjobs where supercronic is being launched with CMD as a last line in dockerfile, so it basically does only that - runs supercronic. 

This container is using my php container as a base (FROM myphpcontainername), it shares env variables with use of docker-compose file, and shares same volumes as my phpcontainer.

I think this is quite convenient, because I got cronjobs completely separated from rest of the environment. So far so good, seems to be working!

@krallin thank you so much for Supercronic. If I had any hair left I would probably pull it off already, trying to run regular cron in a container where I am not a root.
