### ISSUE TITLE
Health checks

### ISSUE THREAD

**Issue by zuzzas** [aptible/supercronic#17]
This is a feature request.

Hello.

Would it be possible to add a health check to supercronic? Should be as simple as this: https://www.ianlewis.org/en/using-kubernetes-health-checks

Rationale: a lot of containers nowadays run under the orchestration software, such as Kubernetes. All of them has health checking primitives that allows failed services inside containers to restart. Usually, it just listens on a TCP socket, and responds to HTTP GET requests with an HTTP OK.

**Comment by krallin** [comment]
Kubernetes (and other container orchestration systems) should detect containers that exit without a HTTP health check. Can you clarify your use case and explain why this does not work for you?

**Comment by zuzzas** [comment]
That is true. Unfortunately, software can fail without correctly terminating itself. Hence, the need for health checks. For example, workers, that execute cron jobs, might silently fail (due to unforeseen bugs). Perhaps, every required check is already in place, and any error will kill the process?

BTW, I am not speaking from any experience, my exposure to Go is rather limited. The only thing that I want is a fault-tolerant system.

**Comment by krallin** [comment]
Then, what you're asking for is for Supercronic to be able to introspect itself to figure out "am I working properly right now?", and expose this information over a HTTP server.

Without this introspection capability, health checks are a (useless) red herring: there's absolutely no reason to think an ad-hoc health-check HTTP server would stop working if Supercronic faield without exiting.

That said, note that _if Supercronic had this introspection capability_, then it might as well make sure to exit when it detects that it's not working properly (or recover)... which makes the HTTP health redundant.

---

In other words, your feature request here is really about Supercronic detecting when it stops working, as you say, _"due to unforeseen bugs"_.

Unfortunately, the nature of unforeseen bugs being that they're unforeseen. I don't think anyone could come up with a list of "required checks" that should be in place to prevent those, and I don't think Supercronic (or any software) should reasonably claim to handle all unforeseen bugs.

(that said, I do try to make sure to fix bugs that cause silent failures — e.g. in a840065d5dde363dc4efafa266d6ae29cc421b08 — I just can't promise I fixed all of them).

---

In other words, when faced with a theoretical failure condition that prevents Supercronic from working, we have a few options:

1) Expose its occurence in a health check (what you're asking for).
2) Crash.
3) Alter the code to make the failure condition impossible in the first place.

In a complex piece of software, solution 1) might make sense, but Supercronic is a fairly simple codebase, where solutions 3) and 2) are always going to be better choices.

---

That said, no one should claim their software is bug free, and I won't make this claim for Supercronic. It's entirely possible that there are bugs that will cause it to silently fail (#13 fixed one such bug). So, I encourage you (and all users of Supercronic )  to monitor your cron jobs using a cron monitoring tool 😄 

(I personally like [Dead Man's Snitch](https://deadmanssnitch.com), but i'm sure there are plenty of other great options)

**Comment by zuzzas** [comment]
Damn, you've put it quite eloquently, thanks! I am going to look into using some kind of cron monitoring tool. Seems like a general (not SaaS) solution might be hidden somewhere. :)

**Comment by krallin** [comment]
Sounds good, happy to help :)
