### ISSUE TITLE
supercronic logs "error running command: waitid: no child processes" regulary since v0.2.31

### ISSUE THREAD

**Issue by ceesgeene** [aptible/supercronic#171]
Since https://github.com/aptible/supercronic/releases/tag/v0.2.31 we regulary see superconic logging errors with the following message: "error running command: waitid: no child processes"

In that release ramr/go-reaper was added to automatically reap zombie processes (see https://github.com/aptible/supercronic/pull/164/commits/8e8973c1d1b13515076ccbbbb38a3a846b4429fa ).

For that library there already exists a similar issue: https://github.com/ramr/go-reaper/issues/11

One of the suggestions (https://github.com/ramr/go-reaper/issues/11#ref-pullrequest-638107175) is to use a more verbose chunk of code so that the reaper runs inside a different process: https://github.com/ramr/go-reaper?tab=readme-ov-file#into-the-woods . Not sure if this is applicable to supercronic

**Comment by UserNotFound** [comment]
Hi @ceesgeene, can you clarify if there is any impact beyond logging the error?

Pinging @qianlongzt in case you're able to assist with a triage or fix.

**Comment by qianlongzt** [comment]
The impact is just random (not 100%) waitid errors. The CronsFailCounter may incorrect


Perhaps the fix is to run the reaper first and then start supercronic as its child?


https://github.com/aptible/supercronic/blob/master/cron/cron.go#L256
https://github.com/aptible/supercronic/blob/master/cron/cron.go#L119

![image](https://github.com/user-attachments/assets/f360ca30-0f13-4ad7-a974-0761e86de8cc)

**Comment by jonasgeiler** [comment]
I am having the same problem. Funnily enough it seems like using `--init` when running the container mitigates this problem? Or maybe I just never witnessed it when using `--init`. As @qianlongzt said, it is very random.
